import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const BUCKET="city-apps";
const apps:Record<string,{origin:string;seeds?:string[]}>= {
 spectra:{origin:"https://prairie-dream-glow-fire.grok.me"}, fold:{origin:"https://giant-beacon-dawn-falcon.grok.me"}, murmuration:{origin:"https://kite-glade-tiger-cabin.grok.me"}, mnemosyne:{origin:"https://moon-clear-urban-nova.grok.me"}, density:{origin:"https://winter-dawn-leaf-marble.grok.me"}, horizon:{origin:"https://zenith-fjord-pearl-pixel.grok.me"}, wave:{origin:"https://apex-star-crisp-blend.grok.me"}, identity:{origin:"https://mist-mint-branch-nova.grok.me"}, build:{origin:"https://brave-ivory-pearl-ever.grok.me"}, soar:{origin:"https://topaz-solar-iris-drift.grok.me"}, scalar:{origin:"https://heart-eagle-blade-hazel.grok.me"}, eidolon:{origin:"https://lark-plaza-umbra-drum.grok.me"}, kartekeya:{origin:"https://velvet-king-quiet-amber.grok.me"}, see:{origin:"https://orbit-coral-delta-fjord.grok.me",seeds:["/","/kernel","/transit","/lineage"]}, cube:{origin:"https://garden-king-granite-pixel.grok.me"},
 "city-os":{origin:"https://spark-maple-sail-tiger.grok.me"}, matrix:{origin:"https://oasis-acorn-pearl-prism.grok.me"}, chimera:{origin:"https://zest-blade-turbo-rose.grok.me",seeds:["/","/lab","/hars","/walk","/theorems","/qegt"]}, sigillum:{origin:"https://prism-shadow-sage-craft.grok.me"}, "proof-forge":{origin:"https://pepper-raven-blade-heart.grok.me"}, invarifold:{origin:"https://sapphire-cabin-crystal-king.grok.me",seeds:["/","/forge"]}, gestalt:{origin:"https://tundra-drift-dune-finch.grok.me",seeds:["/","/sheet","/kernel","/spectral","/chain","/field","/city","/applications"]},
 "ufo-propulsion":{origin:"https://star-sage-atlas-rapid.grok.me"}, "eidolon-harmonic":{origin:"https://nova-wood-clear-zest.grok.me"}, "hover-build":{origin:"https://willow-fjord-king-cap.grok.me"}, hover:{origin:"https://bison-drum-daisy-plaza.grok.me"}, mav:{origin:"https://glow-garden-brick-cedar.grok.me"}
};
function secretKey(){const r=Deno.env.get("SUPABASE_SECRET_KEYS");if(r)return JSON.parse(r).default;const l=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(l)return l;throw new Error("No secret key")}
const sb=createClient(Deno.env.get("SUPABASE_URL")!,secretKey(),{auth:{persistSession:false,autoRefreshToken:false}});
const TEXT=["text/","javascript","json","xml","svg","manifest"];
const ASSET=/\.(?:js|mjs|css|json|map|wasm|svg|png|jpe?g|webp|gif|ico|avif|woff2?|ttf|otf|webmanifest|mp3|mp4|webm)(?:$|[?#])/i;
function clean(p:string){p=p.replace(/^\/+/,"");if(!p)return"index.html";if(p.endsWith("/"))return p+"index.html";const x=p.split("/").pop()||"";return x.includes(".")?p:p+"/index.html"}
function discover(text:string,current:URL,origin:string){const out=new Set<string>();const add=(raw:string)=>{if(!raw||/^(?:data:|blob:|mailto:|javascript:)/.test(raw))return;try{const u=new URL(raw.replace(/&amp;/g,"&"),current);if(u.origin!==origin)return;u.hash="";if(u.pathname==="/"||u.pathname.startsWith("/assets/")||u.pathname.startsWith("/__grok/")||ASSET.test(u.pathname))out.add(u.toString())}catch{}};for(const m of text.matchAll(/(?:src|href|poster|content)\s*=\s*["']([^"']+)["']/gi))add(m[1]);for(const m of text.matchAll(/url\(\s*["']?([^"')\s]+)["']?\s*\)/gi))add(m[1]);return[...out]}
async function bucket(){const{data,error}=await sb.storage.listBuckets();if(error)throw error;if(!(data||[]).some((b:any)=>b.name===BUCKET)){const r=await sb.storage.createBucket(BUCKET,{public:false});if(r.error)throw r.error}}
async function save(path:string,buf:Uint8Array,ct:string){const{error}=await sb.storage.from(BUCKET).upload(path,buf,{contentType:ct||"application/octet-stream",cacheControl:"31536000",upsert:true});if(error)throw error}
async function migrate(slug:string){const spec=apps[slug];if(!spec)throw new Error(`Unknown app ${slug}`);await bucket();const q=(spec.seeds||["/"]).map(p=>new URL(p,spec.origin).toString());const seen=new Set<string>(),copied:any[]=[],failed:any[]=[];let bytes=0;while(q.length&&seen.size<240&&bytes<150*1024*1024){const raw=q.shift()!;let u:URL;try{u=new URL(raw)}catch{continue}u.hash="";const key=u.toString();if(seen.has(key)||u.origin!==spec.origin)continue;seen.add(key);try{const r=await fetch(u,{redirect:"follow",headers:{"user-agent":"Mathematical-City-Migrator/2.0"}});if(!r.ok){failed.push({url:key,status:r.status});continue}const ct=(r.headers.get("content-type")||"application/octet-stream").split(";")[0];const buf=new Uint8Array(await r.arrayBuffer());bytes+=buf.byteLength;const path=`${slug}/${clean(u.pathname)}`;await save(path,buf,ct);copied.push({url:key,path,bytes:buf.byteLength,type:ct});if(TEXT.some(t=>ct.includes(t))&&buf.byteLength<10*1024*1024){const text=new TextDecoder().decode(buf);for(const d of discover(text,u,spec.origin))if(!seen.has(d))q.push(d)}}catch(e){failed.push({url:key,error:e instanceof Error?e.message:String(e)})}}
const manifest={schema:"CITY-APP-MIGRATION-2.0",slug,source_origin:spec.origin,migrated_at:new Date().toISOString(),file_count:copied.length,total_bytes:bytes,truncated:q.length>0,copied,failed};await save(`${slug}/migration-manifest.json`,new TextEncoder().encode(JSON.stringify(manifest,null,2)),"application/json");return manifest}
Deno.serve(async(req)=>{if(req.method!=="GET")return Response.json({error:"GET only"},{status:405});const app=new URL(req.url).searchParams.get("app");if(!app)return Response.json({allowed:Object.keys(apps)});try{return Response.json(await migrate(app),{headers:{"cache-control":"no-store"}})}catch(e){return Response.json({app,error:e instanceof Error?e.message:String(e)},{status:500})}});
