import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "postgres";
import { LabError, prepareLabRun } from "./lab-adapters.ts";

const sql = postgres(Deno.env.get("SUPABASE_DB_URL")!, { prepare:false, max:1 });
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const PACKET_URL = `${SUPABASE_URL}/functions/v1/city-mini-labs`;
const ZERO = "0".repeat(64);
const ID = Array.from({length:125},(_,i)=>i);
const BASE=["R","L","U","D","F","B","L2","M","R2","B2","S","F2","D2","E","U2"] as const;
const SPEC:Record<string,["x"|"y"|"z",number,number]>={R:["x",4,1],L:["x",0,-1],U:["y",4,1],D:["y",0,-1],F:["z",4,1],B:["z",0,-1],R2:["x",3,1],M:["x",2,-1],L2:["x",1,-1],F2:["z",3,1],S:["z",2,1],B2:["z",1,-1],U2:["y",3,1],E:["y",2,-1],D2:["y",1,-1]};
const CORS={"access-control-allow-origin":"*","access-control-allow-headers":"authorization,content-type,x-agent-name","access-control-allow-methods":"GET,POST,OPTIONS"};
class AppError extends Error{constructor(public status:number,message:string){super(message)}}
const coords=(i:number):[number,number,number]=>[Math.floor(i/25),Math.floor(i/5)%5,i%5];
const idx=(x:number,y:number,z:number)=>25*x+5*y+z;
function rot(x:number,y:number,z:number,a:string,d:number):[number,number,number]{if(a==="x"){let Y=y-2,Z=z-2;[Y,Z]=d>0?[-Z,Y]:[Z,-Y];return[x,Math.round(Y+2),Math.round(Z+2)]}if(a==="y"){let X=x-2,Z=z-2;[X,Z]=d>0?[Z,-X]:[-Z,X];return[Math.round(X+2),y,Math.round(Z+2)]}let X=x-2,Y=y-2;[X,Y]=d>0?[-Y,X]:[Y,-X];return[Math.round(X+2),Math.round(Y+2),z]}
function parseMove(m:string){const prime=m.endsWith("'");const base=prime?m.slice(0,-1):m;const s=SPEC[base];if(!s)throw new AppError(400,`invalid move: ${m}`);return{base,axis:s[0],layer:s[1],dir:s[2]*(prime?-1:1)}}
function applyMove(state:number[],m:string){const{axis,layer,dir}=parseMove(m);const out=state.slice();for(let p=0;p<125;p++){const[x,y,z]=coords(p),c={x,y,z};if(c[axis]!==layer)continue;const[X,Y,Z]=rot(x,y,z,axis,dir);out[idx(X,Y,Z)]=state[p]}return out}
const inv=(m:string)=>m.endsWith("'")?m.slice(0,-1):m+"'";
function metrics(state:number[]){let displaced=0,e=0;for(let p=0;p<125;p++){const cubie=state[p];if(cubie!==p)displaced++;const[x,y,z]=coords(p),[a,b,c]=coords(cubie);e+=(x-a)**2+(y-b)**2+(z-c)**2}return{displaced,geometry_energy:e/125}}
function bijective(s:number[]){return s.length===125&&new Set(s).size===125&&s.every(v=>Number.isInteger(v)&&v>=0&&v<125)}
function rng(seed:number){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let r=Math.imul(t^(t>>>15),1|t);r^=r+Math.imul(r^(r>>>7),61|r);return((r^(r>>>14))>>>0)/4294967296}}
function scramble(seed:number,depth:number){const R=rng(seed),out:string[]=[];let prev="";for(let i=0;i<depth;i++){let b="";do{b=BASE[Math.floor(R()*BASE.length)]}while(b===prev&&BASE.length>1);prev=b;out.push(R()<.5?b:b+"'")}return out}
async function sha256(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(v)));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function claims(req:Request){const h=req.headers.get("authorization")||"",token=h.replace(/^Bearer\s+/i,"");const parts=token.split(".");if(parts.length<2)throw new AppError(401,"missing bearer token");try{let s=parts[1].replace(/-/g,"+").replace(/_/g,"/");s+="=".repeat((4-s.length%4)%4);const p=JSON.parse(atob(s)),actor=p.sub||p.role;if(!actor)throw 0;return{actor:String(actor),role:String(p.role||"")}}catch{throw new AppError(401,"invalid bearer token")}}
function agent(req:Request,fallback="city-cube-bus"){return(req.headers.get("x-agent-name")||fallback).slice(0,128)}
function auth(owner:string,c:{actor:string,role:string}){if(c.role!=="service_role"&&owner!==c.actor)throw new AppError(403,"resource belongs to another subject")}
async function packetCall(body:any){const r=await fetch(PACKET_URL,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({error:`packet endpoint ${r.status}`}));if(!r.ok||j?.error)throw new AppError(400,j?.error||`packet endpoint ${r.status}`);return j}
function normalizeCube(r:any){return{...r,seed:Number(r.seed),move_count:Number(r.move_count),ledger_seq:Number(r.ledger_seq)}}
function cubeView(r:any){r=normalizeCube(r);const m=metrics(r.permutation);return{id:r.id,owner_sub:r.owner_sub,status:r.status,seed:r.seed,move_count:r.move_count,ledger_seq:r.ledger_seq,head_hash:r.head_hash,metrics:m,certificate:{bijective:bijective(r.permutation),identity:m.displaced===0},carrier:{shape:[5,5,5],dimension:125},e47:{dimension:47,omega_c:47/125}}}
async function loadCube(tx:any,id:string){const a=await tx`select id::text,seed,status,permutation,word,move_count,ledger_seq,head_hash,owner_sub,metadata,created_at,updated_at from public.cube_instances where id=${id}::uuid for update`;if(!a.length)throw new AppError(404,"cube instance not found");return normalizeCube(a[0])}
async function loadBinding(tx:any,experimentId:string){const a=await tx`select id::text,experiment_id,packet_schema_version,cube_instance_id::text,owner_sub,packet,packet_hash,cube_head_hash,cube_ledger_seq,event_seq,bus_head_hash,status,last_module,metadata,created_at,updated_at from public.cube_packet_bindings where experiment_id=${experimentId} for update`;if(!a.length)throw new AppError(404,"cube packet binding not found");return{...a[0],cube_ledger_seq:Number(a[0].cube_ledger_seq),event_seq:Number(a[0].event_seq)}}
async function saveCube(tx:any,row:any){await tx`update public.cube_instances set status=${row.status},permutation=${JSON.stringify(row.permutation)}::jsonb,word=${JSON.stringify(row.word)}::jsonb,move_count=${row.move_count},ledger_seq=${row.ledger_seq},head_hash=${row.head_hash},owner_sub=${row.owner_sub},metadata=${JSON.stringify(row.metadata||{})}::jsonb where id=${row.id}::uuid`}
async function appendCubeEvent(tx:any,row:any,kind:string,move:string|null,actor:string,module:string,details:any){const seq=Number(row.ledger_seq)+1,prev=row.head_hash,met=metrics(row.permutation),full={...details,module};const hash=await sha256({instance_id:row.id,seq,kind,move,actor,prev_hash:prev,permutation:row.permutation,details:full});await tx`insert into public.cube_moves(instance_id,seq,kind,move,source,prev_hash,hash,displaced,geometry_energy,permutation,actor,details) values(${row.id}::uuid,${seq},${kind},${move},${module},${prev},${hash},${met.displaced},${met.geometry_energy},${JSON.stringify(row.permutation)}::jsonb,${actor},${JSON.stringify(full)}::jsonb)`;row.ledger_seq=seq;row.head_hash=hash;return{seq,hash,...met}}
async function applyWord(tx:any,row:any,word:string[],kind:string,actor:string,module:string,details:any){for(const mv of word){row.permutation=applyMove(row.permutation,mv);row.word=[...row.word,mv];row.move_count++;await appendCubeEvent(tx,row,kind,mv,actor,module,details)}}
function snap(row:any){const m=metrics(row.permutation);return{cube_instance_id:row.id,head_hash:row.head_hash,ledger_seq:Number(row.ledger_seq),move_count:Number(row.move_count),status:row.status,displaced:m.displaced,geometry_energy:m.geometry_energy}}
async function mutateCube(tx:any,row:any,cmd:any,actor:string,module:string,experimentId:string,packetHash:string){const before=snap(row),action=String(cmd?.action||"snapshot");let word:string[]=[];
  const details={experiment_id:experimentId,packet_hash:packetHash,module};
  if(action==="snapshot")return{operation:{action},before,after:before};
  if(action==="move"){const mv=String(cmd.move||"");parseMove(mv);word=[mv];await applyWord(tx,row,word,"move",actor,module,details);row.status=metrics(row.permutation).displaced?"active":"solved"}
  else if(action==="scramble"){const depth=Math.max(1,Math.min(200,Math.trunc(Number(cmd.depth||12)))),seed=Math.max(0,Number.isFinite(Number(cmd.seed))?Math.trunc(Number(cmd.seed)):row.seed+row.move_count+1);word=scramble(seed,depth);await applyWord(tx,row,word,"scramble",actor,module,{...details,seed,depth});row.status=metrics(row.permutation).displaced?"scrambled":"solved"}
  else if(action==="solve"){word=[...row.word].reverse().map(inv);if(word.length){for(const mv of word){row.permutation=applyMove(row.permutation,mv);row.move_count++;await appendCubeEvent(tx,row,"solve",mv,actor,module,{...details,solution_length:word.length})}}else await appendCubeEvent(tx,row,"solve",null,actor,module,{...details,noop:true});row.word=[];row.status="solved";if(!row.permutation.every((v:number,i:number)=>v===i))throw new AppError(500,"inverse solution failed identity check")}
  else if(action==="reset"){row.permutation=ID.slice();row.word=[];row.status="solved";await appendCubeEvent(tx,row,"reset",null,actor,module,{...details,reason:String(cmd.reason||"packet-bus reset")})}
  else throw new AppError(400,"cube_command.action must be snapshot, move, scramble, solve, or reset");
  await saveCube(tx,row);return{operation:{action,word},before,after:snap(row)}
}
async function appendBusEvent(tx:any,b:any,input:any){const seq=Number(b.event_seq)+1,prev=b.bus_head_hash,core={binding_id:b.id,seq,event_type:input.event_type,module:input.module,operation:input.operation,packet_stage:input.packet_stage??null,packet_hash_before:input.packet_hash_before??null,packet_hash_after:input.packet_hash_after??null,cube_head_before:input.cube_head_before,cube_head_after:input.cube_head_after,cube_ledger_before:input.cube_ledger_before,cube_ledger_after:input.cube_ledger_after,actor:input.actor,details:input.details??{}};const hash=await sha256({...core,prev_hash:prev});await tx`insert into public.cube_packet_events(binding_id,seq,event_type,module,operation,packet_stage,packet_hash_before,packet_hash_after,cube_head_before,cube_head_after,cube_ledger_before,cube_ledger_after,prev_hash,hash,actor,details) values(${b.id}::uuid,${seq},${core.event_type},${core.module},${core.operation},${core.packet_stage},${core.packet_hash_before},${core.packet_hash_after},${core.cube_head_before},${core.cube_head_after},${core.cube_ledger_before},${core.cube_ledger_after},${prev},${hash},${core.actor},${JSON.stringify(core.details)}::jsonb)`;b.event_seq=seq;b.bus_head_hash=hash;return{seq,hash}}
async function saveBinding(tx:any,b:any){await tx`update public.cube_packet_bindings set owner_sub=${b.owner_sub},packet=${JSON.stringify(b.packet)}::jsonb,packet_hash=${b.packet_hash},cube_head_hash=${b.cube_head_hash},cube_ledger_seq=${b.cube_ledger_seq},event_seq=${b.event_seq},bus_head_hash=${b.bus_head_hash},status=${b.status},last_module=${b.last_module},metadata=${JSON.stringify(b.metadata||{})}::jsonb,updated_at=now() where id=${b.id}::uuid`}
function bindingView(b:any){return{id:b.id,experiment_id:b.experiment_id,packet_schema_version:b.packet_schema_version,cube_instance_id:b.cube_instance_id,owner_sub:b.owner_sub,packet_hash:b.packet_hash,cube_head_hash:b.cube_head_hash,cube_ledger_seq:Number(b.cube_ledger_seq),event_seq:Number(b.event_seq),bus_head_hash:b.bus_head_hash,status:b.status,last_module:b.last_module,lab_states:b.metadata?.lab_states??{},updated_at:b.updated_at}}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});try{const c=claims(req),moduleHeader=agent(req);const u=new URL(req.url);
  if(req.method==="GET"){const experimentId=u.searchParams.get("experiment_id");if(!experimentId)return Response.json({service:"city-cube-bus",version:2,packet_schema:"MC-OCTET-PACKET-1.0",resource:"persistent Cube",semantics:"Cube is a shared typed resource, not an additional packet stage",supported_modules:["SPECTRA","Fold","Density","Murmuration","Horizon","Mnemosyne","Wave","Identity","BUILD","SOAR","Proof Forge","agent:*"],actions:["lab_run","bind","stage_advance","resource_op","sync","handoff","close"]},{headers:CORS});const out=await sql.begin(async tx=>{const b=await loadBinding(tx,experimentId);auth(b.owner_sub,c);const cube=await loadCube(tx,b.cube_instance_id);const history=u.searchParams.get("history")==="1"?await tx`select seq,created_at,event_type,module,operation,packet_stage,packet_hash_before,packet_hash_after,cube_head_before,cube_head_after,cube_ledger_before,cube_ledger_after,prev_hash,hash,actor,details from public.cube_packet_events where binding_id=${b.id}::uuid order by seq asc limit 500`:undefined;return{binding:bindingView(b),packet:b.packet,cube:cubeView(cube),synchronized:b.cube_head_hash===cube.head_hash&&Number(b.cube_ledger_seq)===Number(cube.ledger_seq),history}});return Response.json(out,{headers:CORS})}
  if(req.method!=="POST")throw new AppError(405,"use GET or POST");const body=await req.json(),action=String(body.action||"");
  if(action==="bind"){const experimentId=String(body.experiment_id||"").trim(),cubeId=String(body.cube_id||"").trim();if(!experimentId||!cubeId)throw new AppError(400,"experiment_id and cube_id required");let packet=body.packet;if(!packet){const made=await packetCall({action:"packet_create",experiment_id:experimentId,input:body.input??{cube_instance_id:cubeId},declaration:body.declaration??{},evidence_class:body.evidence_class??"workflow"});packet=made.packet}const ver=await packetCall({action:"packet_verify",packet});if(!ver.valid)throw new AppError(400,`packet invalid: ${(ver.errors||[]).join("; ")}`);if(packet.experiment_id!==experimentId)throw new AppError(400,"packet experiment_id mismatch");const result=await sql.begin(async tx=>{const cube=await loadCube(tx,cubeId);auth(cube.owner_sub,c);const existing=await tx`select id from public.cube_packet_bindings where experiment_id=${experimentId} or (cube_instance_id=${cubeId}::uuid and status='active') limit 1`;if(existing.length)throw new AppError(409,"experiment or Cube already has an active binding");const owner=c.role==="service_role"?cube.owner_sub:c.actor;const rows=await tx`insert into public.cube_packet_bindings(experiment_id,cube_instance_id,owner_sub,packet,packet_hash,cube_head_hash,cube_ledger_seq,event_seq,bus_head_hash,status,last_module,metadata) values(${experimentId},${cubeId}::uuid,${owner},${JSON.stringify(packet)}::jsonb,${packet.integrity.packet_hash},${cube.head_hash},${cube.ledger_seq},0,${ZERO},'active',${moduleHeader},${JSON.stringify({resource:"Cube",semantics:"shared typed resource; not packet stage"})}::jsonb) returning id::text,experiment_id,packet_schema_version,cube_instance_id::text,owner_sub,packet,packet_hash,cube_head_hash,cube_ledger_seq,event_seq,bus_head_hash,status,last_module,metadata,updated_at`;const b={...rows[0],cube_ledger_seq:Number(rows[0].cube_ledger_seq),event_seq:0};const before=snap(cube);const ev=await appendBusEvent(tx,b,{event_type:"bind",module:moduleHeader,operation:"bind",packet_hash_before:null,packet_hash_after:b.packet_hash,cube_head_before:before.head_hash,cube_head_after:before.head_hash,cube_ledger_before:before.ledger_seq,cube_ledger_after:before.ledger_seq,actor:c.actor,details:{packet_valid:true}});await saveBinding(tx,b);return{binding:bindingView(b),packet:b.packet,cube:cubeView(cube),event:ev}});return Response.json(result,{headers:CORS})}
  const experimentId=String(body.experiment_id||"").trim();if(!experimentId)throw new AppError(400,"experiment_id required");const result=await sql.begin(async tx=>{const b=await loadBinding(tx,experimentId);auth(b.owner_sub,c);if(b.status!=="active"&&action!=="sync")throw new AppError(409,"binding is closed");const cube=await loadCube(tx,b.cube_instance_id);auth(cube.owner_sub,c);const module=String(body.module||moduleHeader||"agent").slice(0,128);const packetVer=await packetCall({action:"packet_verify",packet:b.packet});if(!packetVer.valid)throw new AppError(409,`stored packet failed verification: ${(packetVer.errors||[]).join("; ")}`);
    if(action==="sync"){const oldHead=b.cube_head_hash,oldSeq=Number(b.cube_ledger_seq),after=snap(cube);b.cube_head_hash=after.head_hash;b.cube_ledger_seq=after.ledger_seq;b.last_module=module;const ev=await appendBusEvent(tx,b,{event_type:"sync",module,operation:"sync",packet_hash_before:b.packet_hash,packet_hash_after:b.packet_hash,cube_head_before:oldHead,cube_head_after:after.head_hash,cube_ledger_before:oldSeq,cube_ledger_after:after.ledger_seq,actor:c.actor,details:{drift_detected:oldHead!==after.head_hash||oldSeq!==after.ledger_seq}});await saveBinding(tx,b);return{binding:bindingView(b),cube:cubeView(cube),packet:b.packet,event:ev}}
    if(b.cube_head_hash!==cube.head_hash||Number(b.cube_ledger_seq)!==Number(cube.ledger_seq))throw new AppError(409,"Cube head drift detected; call sync before operating through the bus");
    if(action==="lab_run"){
      const run=await prepareLabRun(body,b), state=snap(cube);
      const ev=await appendBusEvent(tx,b,{event_type:"resource_op",module:run.module,operation:"lab_run",
        packet_stage:b.packet.next_stage??null,packet_hash_before:b.packet_hash,packet_hash_after:b.packet_hash,
        cube_head_before:state.head_hash,cube_head_after:state.head_hash,
        cube_ledger_before:state.ledger_seq,cube_ledger_after:state.ledger_seq,actor:c.actor,details:run.details});
      b.metadata={...b.metadata,lab_states:{...b.metadata?.lab_states,[run.module]:{...run.checkpoint,event_seq:b.event_seq}}};
      b.last_module=run.module;
      await saveBinding(tx,b);
      return{binding:bindingView(b),packet:b.packet,cube:cubeView(cube),result:run.details.result,event:ev};
    }
    if(action==="resource_op"){const transition=await mutateCube(tx,cube,body.cube_command??{action:"snapshot"},c.actor,module,experimentId,b.packet_hash);b.cube_head_hash=transition.after.head_hash;b.cube_ledger_seq=transition.after.ledger_seq;b.last_module=module;const ev=await appendBusEvent(tx,b,{event_type:"resource_op",module,operation:transition.operation.action,packet_stage:b.packet.next_stage??null,packet_hash_before:b.packet_hash,packet_hash_after:b.packet_hash,cube_head_before:transition.before.head_hash,cube_head_after:transition.after.head_hash,cube_ledger_before:transition.before.ledger_seq,cube_ledger_after:transition.after.ledger_seq,actor:c.actor,details:{cube_transition:transition.operation,boundary:"Resource operation does not advance packet or promote evidence class."}});await saveBinding(tx,b);return{binding:bindingView(b),packet:b.packet,cube:cubeView(cube),transition,event:ev}}
    if(action==="stage_advance"){const stage=String(body.stage||"");if(!stage)throw new AppError(400,"stage required");const transition=await mutateCube(tx,cube,body.cube_command??{action:"snapshot"},c.actor,module,experimentId,b.packet_hash);const resourceWitness={experiment_id:experimentId,cube_instance_id:cube.id,module,operation:transition.operation,before:transition.before,after:transition.after,bus_semantics:"shared typed resource witness; Cube is not a packet stage"};const advanced=await packetCall({action:"packet_advance",packet:b.packet,stage,payload:{...(body.payload??{}),cube_resource:resourceWitness},diagnostics:{...(body.diagnostics??{}),cube_head_bound:true},source_ref:body.source_ref??`cube:${cube.id}`,evidence_class:body.evidence_class,stage_version:body.stage_version});const nextPacket=advanced.packet,oldPacketHash=b.packet_hash;b.packet=nextPacket;b.packet_hash=nextPacket.integrity.packet_hash;b.cube_head_hash=transition.after.head_hash;b.cube_ledger_seq=transition.after.ledger_seq;b.last_module=module;const ev=await appendBusEvent(tx,b,{event_type:"stage",module,operation:transition.operation.action,packet_stage:stage,packet_hash_before:oldPacketHash,packet_hash_after:b.packet_hash,cube_head_before:transition.before.head_hash,cube_head_after:transition.after.head_hash,cube_ledger_before:transition.before.ledger_seq,cube_ledger_after:transition.after.ledger_seq,actor:c.actor,details:{stage_output_hash:nextPacket.stages.at(-1)?.output_hash,stage_hash:nextPacket.stages.at(-1)?.stage_hash}});await saveBinding(tx,b);return{binding:bindingView(b),packet:nextPacket,cube:cubeView(cube),transition,event:ev}}
    if(action==="handoff"){const target=String(body.target_owner_sub||"").trim();if(!target)throw new AppError(400,"target_owner_sub required");const before=snap(cube),from=b.owner_sub;await appendCubeEvent(tx,cube,"handoff",null,c.actor,module,{experiment_id:experimentId,packet_hash:b.packet_hash,from,to:target});cube.owner_sub=target;await saveCube(tx,cube);const after=snap(cube);b.owner_sub=target;b.cube_head_hash=after.head_hash;b.cube_ledger_seq=after.ledger_seq;b.last_module=module;const ev=await appendBusEvent(tx,b,{event_type:"handoff",module,operation:"handoff",packet_stage:b.packet.next_stage??null,packet_hash_before:b.packet_hash,packet_hash_after:b.packet_hash,cube_head_before:before.head_hash,cube_head_after:after.head_hash,cube_ledger_before:before.ledger_seq,cube_ledger_after:after.ledger_seq,actor:c.actor,details:{from,to:target}});await saveBinding(tx,b);return{binding:bindingView(b),packet:b.packet,cube:cubeView(cube),event:ev}}
    if(action==="close"){const s=snap(cube);b.status="closed";b.last_module=module;const ev=await appendBusEvent(tx,b,{event_type:"close",module,operation:"close",packet_stage:b.packet.next_stage??null,packet_hash_before:b.packet_hash,packet_hash_after:b.packet_hash,cube_head_before:s.head_hash,cube_head_after:s.head_hash,cube_ledger_before:s.ledger_seq,cube_ledger_after:s.ledger_seq,actor:c.actor,details:{reason:String(body.reason||"explicit close")}});await saveBinding(tx,b);return{binding:bindingView(b),packet:b.packet,cube:cubeView(cube),event:ev}}
    throw new AppError(400,"action must be lab_run, bind, stage_advance, resource_op, sync, handoff, or close")});return Response.json(result,{headers:CORS})
}catch(e){const status=(e instanceof AppError||e instanceof LabError)?e.status:500;return Response.json({error:e instanceof Error?e.message:String(e)},{status,headers:CORS})}});

