const assert = require("node:assert/strict");
const { readFileSync, existsSync } = require("node:fs");
const { resolve } = require("node:path");
const { test } = require("node:test");

const root = resolve(__dirname, "..");
const lockJs = readFileSync(resolve(root, "website/interfaces/shared/e47-lock.js"), "utf8");
const json = JSON.parse(readFileSync(resolve(root, "website/data/e47-canonical-kernel.json"), "utf8"));
const runtime = readFileSync(resolve(root, "website/interfaces/skyrmion/runtime2/e47-runtime.js"), "utf8");
const binding = readFileSync(resolve(root, "website/interfaces/shared/e47-kernel-binding.js"), "utf8");
const world = readFileSync(resolve(root, "website/interfaces/skyrmion/world-runtime.js"), "utf8");
const home = readFileSync(resolve(root, "website/index.html"), "utf8");
const core = readFileSync(resolve(root, "website/interfaces/kouns-core/index.html"), "utf8");
const shell = readFileSync(resolve(root, "website/interfaces/flight/flight-shell.js"), "utf8");

test("generated lock matches frozen E47 object", () => {
  assert.equal(json.authority, "src/e47/spectral_compilation.py");
  assert.equal(json.canonical.carrier_dimension, 125);
  assert.equal(json.canonical.kernel_dimension, 47);
  assert.equal(json.canonical.coherence_fraction, "47/125");
  assert.deepEqual(json.canonical.casimir_roots, [6, 30]);
  assert.deepEqual(json.canonical.casimir_spectrum, [0, 2, 6, 12, 20, 30, 42]);
  assert.deepEqual(json.canonical.sector_dimensions, [1, 9, 25, 28, 27, 22, 13]);
  assert.equal(json.canonical.epsilon_star, "1/99144");
  assert.ok(lockJs.includes("GENERATED by scripts/generate_browser_kernel_contract.py"));
  assert.ok(lockJs.includes('"coherence_fraction": "47/125"'));
});

test("flight runtimes import the lock instead of copying spectrum literals", () => {
  assert.ok(runtime.includes('from "../../shared/e47-lock.js"'));
  assert.ok(!runtime.includes("const CASIMIR="));
  assert.ok(!runtime.includes("EPS=1/99144"));
  assert.ok(binding.includes('from "./e47-lock.js"'));
  assert.ok(world.includes('from "../shared/e47-lock.js"'));
  assert.ok(core.includes("installCanonicalE47Binding"));
  assert.ok(shell.includes("installCanonicalE47Binding"));
  assert.ok(home.includes("e47-kernel-binding.js"));
});

test("lock file exists for Pages", () => {
  assert.ok(existsSync(resolve(root, "website/interfaces/shared/e47-lock.js")));
  assert.ok(existsSync(resolve(root, "website/data/e47-canonical-kernel.json")));
});
