import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const N=125,J=2,NORM=1814400;
const SCORE:Record<string,number>={full:0,epistemic:.15,abstracted:.55,restricted:1};
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
type Obs={id?:string;epoch?:string;domain:number;implementation:number;operationality:number;outcome?:string;target?:number;weight?:number;training_excluded?:boolean;[key:string]:unknown};
const response=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers:CORS});
const clamp=(x:number)=>Math.max(0,Math.min(1,x));
const dot=(a:ArrayLike<number>,b:ArrayLike<number>)=>{let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s};
const flat=(a:number,b:number,c:number)=>a*25+b*5+c, mval=(i:number)=>2-i;
const jp=(m:number)=>Math.sqrt(Math.max(0,J*(J+1)-m*(m+1))), jm=(m:number)=>Math.sqrt(Math.max(0,J*(J+1)-m*(m-1)));
function pairDot(v:ArrayLike<number>,p:number,q:number){const out=new Float64Array(N);for(let a=0;a<5;a++)for(let b=0;b<5;b++)for(let c=0;c<5;c++){const ix=[a,b,c],k=flat(a,b,c),amp=v[k];if(!amp)continue;const mp=mval(ix[p]),mq=mval(ix[q]);out[k]+=mp*mq*amp;if(ix[p]>0&&ix[q]<4){const y=[a,b,c];y[p]--;y[q]++;out[flat(y[0],y[1],y[2])]+=.5*jp(mp)*jm(mq)*amp}if(ix[p]<4&&ix[q]>0){const y=[a,b,c];y[p]++;y[q]--;out[flat(y[0],y[1],y[2])]+=.5*jm(mp)*jp(mq)*amp}}return out}
function casimir(v:ArrayLike<number>){const a=pairDot(v,0,1),b=pairDot(v,0,2),c=pairDot(v,1,2),out=new Float64Array(N);for(let k=0;k<N;k++)out[k]=18*v[k]+2*(a[k]+b[k]+c[k]);return out}
function factor(v:ArrayLike<number>,s:number){const cv=casimir(v),out=new Float64Array(N);for(let k=0;k<N;k++)out[k]=cv[k]-s*v[k];return out}
function p47(v:ArrayLike<number>){let x=Float64Array.from(v);for(const s of [31,0,2,12,20,42])x=factor(x,s);for(let k=0;k<N;k++)x[k]/=NORM;return x}
function selfTest(){const e=new Float64Array(N);e[0]=1;const p=p47(e),pp=p47(p);let s=0;for(let k=0;k<N;k++)s+=(p[k]-pp[k])**2;return Math.sqrt(s)}
function target(o:Obs){if(Number.isFinite(o.target))return clamp(Number(o.target));if(o.outcome&&o.outcome in SCORE)return SCORE[o.outcome];throw new Error("target or supported outcome required")}
function good(x:unknown){return Number.isInteger(x)&&Number(x)>=0&&Number(x)<=4}
function design(o:Obs,sigma=.72){const r=new Float64Array(N);let z=0,k=0,w=Math.max(Number(o.weight??1),1e-9);for(let d=0;d<5;d++)for(let i=0;i<5;i++)for(let p=0;p<5;p++){const d2=(d-o.domain)**2+(i-o.implementation)**2+(p-o.operationality)**2,x=Math.exp(-d2/(2*sigma*sigma))*w;r[k++]=x;z+=x}for(let i=0;i<N;i++)r[i]/=z;return r}
function art(A:Float64Array[],y:number[]){const x=new Float64Array(N);for(let it=0;it<140;it++)for(let r=0;r<A.length;r++){const a=A[r],fac=.42*(y[r]-dot(a,x))/(dot(a,a)+1e-12);for(let k=0;k<N;k++)x[k]=clamp(x[k]+fac*a[k])}return x}
function order(n:number){const a=Array.from({length:n},(_,i)=>i);let x=47;const rnd=()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296};for(let i=n-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function split(n:number,h:number){const o=order(n),nh=n>=4?Math.max(1,Math.round(n*h)):1,t=new Set(o.slice(0,nh));return{train:o.filter(i=>!t.has(i)),test:o.filter(i=>t.has(i))}}
function rmse(ix:number[],y:number[],p:number[]){if(!ix.length)return null;let s=0;for(const i of ix)s+=(y[i]-p[i])**2;return Math.sqrt(s/ix.length)}
function top(x:ArrayLike<number>){return Array.from({length:N},(_,k)=>k).sort((a,b)=>x[b]-x[a]).slice(0,12).map(k=>({domain:Math.floor(k/25),implementation:Math.floor((k%25)/5),operationality:k%5,score:x[k]}))}
function run(input:Obs[],h=.2){const obs=input.filter(o=>!o.training_excluded);if(obs.length<2||obs.length>500)throw new Error("2..500 non-excluded observations required");for(const o of obs)if(!good(o.domain)||!good(o.implementation)||!good(o.operationality))throw new Error("three coordinates must be integer bins 0..4");const A=obs.map(design),y=obs.map(target),{train,test}=split(obs.length,h),raw=art(train.map(i=>A[i]),train.map(i=>y[i]));let gated=p47(raw);const gt=train.map(i=>dot(A[i],gated));let num=0,den=1e-12;for(let j=0;j<train.length;j++){num+=gt[j]*y[train[j]];den+=gt[j]*gt[j]}const alpha=num/den;gated=Float64Array.from(gated,v=>clamp(alpha*v));const pr=A.map(a=>dot(a,raw)),pg=A.map(a=>dot(a,gated)),rr=rmse(test,y,pr),rg=rmse(test,y,pg);return{schema:"DENSITY-RECONSTRUCT/1.0",carrier:125,coordinates:["domain","implementation","operationality"],gate:{name:"P47",rank:47,projector_selftest_l2:selfTest()},n_observations:obs.length,train_ids:train.map(i=>obs[i].id??String(i)),holdout_ids:test.map(i=>obs[i].id??String(i)),holdout_rmse_raw:rr,holdout_rmse_p47:rg,p47_gate_useful:rr===null||rg===null?null:rg<=rr+.02,observations:obs.map((o,i)=>({...o,target:y[i],pred_raw:pr[i],pred_p47:pg[i],held_out:test.includes(i)})),raw_field:Array.from(raw),p47_field:Array.from(gated),raw_top_cells:top(raw),p47_top_cells:top(gated)}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{headers:CORS});if(req.method==="GET")return response({ok:true,schema:"DENSITY-RECONSTRUCT/1.0",carrier:125,p47_rank:47,projector_selftest_l2:selfTest()});if(req.method!=="POST")return response({error:"POST required"},405);try{const b=await req.json(),o=Array.isArray(b)?b:b.observations,h=Number(b.holdout_fraction??.2);if(!Array.isArray(o))return response({error:"observations array required"},400);return response(run(o,h))}catch(e){return response({error:e instanceof Error?e.message:String(e)},400)}});
