import {SkyrmionRuntime2} from './runtime2.js';
import {VEHICLE_ORDER,vehicle} from './vehicle-registry.js';
const rt=new SkyrmionRuntime2({fixedStepHz:120,spawn:{lat:36.1699,lon:-115.1398,altitudeM:3658,speedMps:216}});window.CITY_SKYRMION_RUNTIME2=rt;
const root=document.getElementById('crafts'),tele=document.getElementById('tele'),gps=document.getElementById('gps'),stick=document.getElementById('stick'),knob=document.getElementById('knob'),proofPanel=document.getElementById('proofPanel');
function syncButtons(){[...root?.children||[]].forEach(q=>q.classList.toggle('on',q.dataset.vehicle===rt.vehicle.id));}
if(root){root.textContent='';VEHICLE_ORDER.forEach((id,i)=>{const b=document.createElement('button');b.textContent=vehicle(id).name;b.dataset.vehicle=id;b.title=vehicle(id).evidence==='conventional'?'Conventional aerodynamic 6DOF':'Experimental simulation adapter';b.classList.toggle('on',i===0);b.onclick=()=>{rt.setVehicle(id);syncButtons();if(id==='manta')initManta();};root.appendChild(b);});}
let drag=false,stickRoll=0,stickPitch=0,keys={};
function setStick(px,py){if(!stick)return;const r=stick.getBoundingClientRect(),dx=Math.max(-1,Math.min(1,(px-r.left-r.width/2)/(r.width*.34))),dy=Math.max(-1,Math.min(1,(py-r.top-r.height/2)/(r.height*.34)));stickRoll=dx;stickPitch=-dy;if(knob)knob.style.transform=`translate(${dx*32}px,${dy*32}px)`;}
stick?.addEventListener('pointerdown',e=>{drag=true;stick.setPointerCapture(e.pointerId);setStick(e.clientX,e.clientY)});stick?.addEventListener('pointermove',e=>{if(drag)setStick(e.clientX,e.clientY)});for(const n of ['pointerup','pointercancel'])stick?.addEventListener(n,()=>{drag=false;stickRoll=stickPitch=0;if(knob)knob.style.transform='none'});
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key>='1'&&e.key<='7')root?.children[+e.key-1]?.click()});addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=0});
addEventListener('skyrmion:teleport',e=>rt.teleport({lat:e.detail?.lat,lon:e.detail?.lon,altitudeM:e.detail?.altitude_m}));addEventListener('skyrmion:manta-frame',e=>rt.mantaFrame=e.detail||null);
function controls(){const roll=stickRoll+(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),pitch=stickPitch+(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),yaw=(keys.e?1:0)-(keys.q?1:0),throttle=keys.shift?1:keys.control?.35:.72;rt.setControls({roll,pitch,yaw,throttle});requestAnimationFrame(controls)}requestAnimationFrame(controls);
let mantaWorker=null,mantaReady=false,mantaBusy=false,lastManta=0;
function initManta(){if(mantaWorker)return;mantaWorker=new Worker('../manta-worker.js');mantaWorker.onmessage=({data})=>{if(data?.type==='ready')mantaReady=true;else if(data?.type==='frame'){mantaBusy=false;rt.mantaFrame=data.state;dispatchEvent(new CustomEvent('skyrmion:manta-frame',{detail:data.state}));}else if(data?.type==='error')mantaBusy=false;};mantaWorker.postMessage({type:'init',schema:'MANTA-PYTHON-BRIDGE-1.0'});}
function stepManta(now){if(rt.vehicle.id==='manta'&&mantaReady&&!mantaBusy&&now-lastManta>34){lastManta=now;mantaBusy=true;const c=rt.state.controls,effort=Math.min(1,Math.hypot(c.pitch,c.roll,c.yaw));mantaWorker.postMessage({type:'step',pilot:{pitch:c.pitch,roll:c.roll,yaw:c.yaw,morph:effort,mode:effort>.45?'MANEUVER':'CRUISE'}});}requestAnimationFrame(stepManta)}requestAnimationFrame(stepManta);
function extendTerrainFleet(){const w=window.CITY_SKYRMION_TERRAIN3D;if(!w?.ready||w.fleet?.length!==6)return false;const jacob=w.fleet[5],sky=jacob.clone(true);sky.name='SKYRMION_RUNTIME2';sky.userData={...jacob.userData,cameraDistance:205,cameraHeight:62,cameraLookAhead:260,runtime2Vehicle:'skyrmion'};sky.scale.multiplyScalar(.92);sky.traverse?.(o=>{if(o.material){o.material=o.material.clone?.()||o.material;o.material.color?.setHex?.(0x6ee7d8);o.material.emissive?.setHex?.(0x082a31);}});sky.visible=false;w.craftRoot.add(sky);w.fleet.splice(5,0,sky);w.setActiveCraft?.(rt.vehicleIndex);return true;}
const fleetTimer=setInterval(()=>{if(extendTerrainFleet())clearInterval(fleetTimer)},120);
addEventListener('skyrmion:runtime2-telemetry',e=>{const d=e.detail;if(tele)tele.textContent=`${d.vehicleName} · ${Math.round(d.speedKt)} KT · ${Math.round(d.altitude_m/0.3048).toLocaleString()} FT · M ${d.mach.toFixed(2)} · Ω ${d.e47.capture.toFixed(3)}`;if(gps){const ns=d.lat>=0?'N':'S',ew=d.lon>=0?'E':'W';gps.textContent=`${Math.abs(d.lat).toFixed(6)}° ${ns} · ${Math.abs(d.lon).toFixed(6)}° ${ew} · ${Math.round(d.altitude_m).toLocaleString()} m`;}syncButtons();if(proofPanel){const p=d.proof;proofPanel.innerHTML=`<b>SKYRMION Runtime 2</b><br>${d.evidence==='conventional'?'CONVENTIONAL 6DOF':'EXPERIMENTAL SIMULATION'} · ${d.propulsion?.adapter||d.propulsion?.engine||''}<br>Mach ${d.mach.toFixed(3)} · q̄ ${Math.round(d.qbar).toLocaleString()} Pa · α ${(d.alpha*180/Math.PI).toFixed(2)}°<br>E47 Ω ${d.e47.capture.toFixed(6)} · residual ${d.e47.residual.toExponential(2)}<br>Proof ${p?.pass===false?'FAIL':'PASS'} · sequence ${p?.sequence||0} · failures ${p?.failures||0}`;}}});
const chip=document.createElement('span');chip.className='chip optional';chip.id='runtime2Status';chip.textContent='RT2 · 120 HZ · 6DOF';document.querySelector('.top')?.appendChild(chip);addEventListener('skyrmion:runtime2-telemetry',e=>{const d=e.detail,p=d.proof;chip.textContent=`RT2 · 120 HZ · 6DOF · ${d.evidence==='conventional'?'AERO':'EXP SIM'} · ${p?.pass===false?'PROOF FAIL':'PROOF OK'}`;chip.classList.toggle('live',p?.pass!==false)});
document.getElementById('proofToggle')?.addEventListener('click',()=>proofPanel?.classList.toggle('open'));
document.getElementById('missionRecord')?.addEventListener('click',e=>{rt.mission.recording=!rt.mission.recording;e.currentTarget.classList.toggle('on',rt.mission.recording);e.currentTarget.textContent=rt.mission.recording?'REC ON':'REC OFF';});
document.getElementById('missionClear')?.addEventListener('click',()=>rt.mission.clear());
document.getElementById('missionReplay')?.addEventListener('click',e=>{if(rt.mission.replaying){rt.stopReplay();e.currentTarget.classList.remove('on');e.currentTarget.textContent='REPLAY';}else if(rt.playReplay()){e.currentTarget.classList.add('on');e.currentTarget.textContent='STOP REPLAY';}});
document.getElementById('missionExport')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(rt.mission.export(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='skyrmion-mission.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
window.CITY_SKYRMION_EXPORT_MISSION=()=>rt.mission.export();window.CITY_SKYRMION_EXPORT_PROOF=()=>rt.exportProof();rt.start();
