import {WorldEngine} from './world-engine.js';
import {SixDOFPhysics} from './physics-6dof.js';
import {VEHICLE_ORDER,vehicle} from './vehicle-registry.js';
import {PropulsionRegistry} from './propulsion-registry.js';
import {E47Runtime} from './e47-runtime.js';
import {MissionReplay} from './mission-replay.js';
import {ProofTelemetry} from './proof-telemetry.js';
import {clamp,norm,qToEuler} from './math.js';
export class SkyrmionRuntime2 extends EventTarget{
 constructor({fixedStepHz=120,spawn={}}={}){super();this.schema='SKYRMION-RUNTIME-2.0';this.fixedStepHz=fixedStepHz;this.dt=1/fixedStepHz;this.world=new WorldEngine();this.physics=new SixDOFPhysics();this.propulsion=new PropulsionRegistry();this.e47=new E47Runtime();this.mission=new MissionReplay();this.proof=new ProofTelemetry();this.vehicleIndex=0;this.vehicle=vehicle(VEHICLE_ORDER[0]);this.state=this.physics.createState(this.vehicle,spawn);this.lastPropulsion={forceBody:[0,0,0],momentBody:[0,0,0],receipt:{mode:'conventional'}};this.accumulator=0;this.lastNow=0;this.running=false;this.mantaFrame=null;this.stepCount=0;}
 setVehicle(id){const next=vehicle(id);const speed=Math.max(80,norm(this.state.velocityBody));this.vehicle=next;this.vehicleIndex=VEHICLE_ORDER.indexOf(next.id);this.state.vehicleId=next.id;this.state.velocityBody=[speed,0,0];this.state.omegaBody=[0,0,0];this.e47.seed(47+Math.max(0,this.vehicleIndex));this.emit();}
 teleport({lat,lon,altitudeM}){if(Number.isFinite(lat))this.state.position.lat=lat;if(Number.isFinite(lon))this.state.position.lon=lon;if(Number.isFinite(altitudeM))this.state.position.altitudeM=altitudeM;this.emit();}
 setControls(c){Object.assign(this.state.controls,{throttle:clamp(c.throttle??this.state.controls.throttle,0,1),pitch:clamp(c.pitch??this.state.controls.pitch,-1,1),roll:clamp(c.roll??this.state.controls.roll,-1,1),yaw:clamp(c.yaw??this.state.controls.yaw,-1,1)});}
 step(){const world=this.world.sample(this.state),V=norm(this.state.velocityBody),sig={alpha:this.state.last.alpha,mach:V/world.speedOfSound,controlNorm:Math.hypot(this.state.controls.pitch,this.state.controls.roll,this.state.controls.yaw)},e47=this.e47.step(sig);this.lastPropulsion=this.propulsion.step(this.vehicle.propulsion,{vehicle:this.vehicle,state:this.state,world,controls:this.state.controls,mach:sig.mach,e47,mantaFrame:this.mantaFrame});this.physics.step(this.vehicle,this.state,world,this.lastPropulsion,this.dt);this.state.position=this.world.integrateGeodetic(this.state.position,this.physics.velocityNed(this.state),this.dt);const telemetry=this.telemetry(world,e47);this.mission.sample(this.state,telemetry,this.dt);if(++this.stepCount%12===0)this.proof.inspect({state:this.state,vehicle:this.vehicle,world,e47,propulsion:this.lastPropulsion,fixedStepHz:this.fixedStepHz});return telemetry;}
 telemetry(world=this.world.sample(this.state),e47=this.e47.snapshot()){const e=qToEuler(this.state.quaternion),speed=norm(this.state.velocityBody);return {schema:this.schema,vehicleId:this.vehicle.id,vehicleName:this.vehicle.name,evidence:this.vehicle.evidence,t:this.state.t,lat:this.state.position.lat,lon:this.state.position.lon,altitude_m:this.state.position.altitudeM,speed,speedKt:speed/0.514444,heading:e.yaw,pitch:e.pitch,roll:e.roll,alpha:this.state.last.alpha,beta:this.state.last.beta,mach:this.state.last.mach,qbar:this.state.last.qbar,world,e47,proof:this.proof.last,propulsion:this.lastPropulsion.receipt};}
 emit(){const d=this.telemetry(),emitGlobal=typeof globalThis.dispatchEvent==='function';if(emitGlobal){globalThis.dispatchEvent(new CustomEvent('skyrmion:flight-state',{detail:{lat:d.lat,lon:d.lon,altitude_m:d.altitude_m,heading:d.heading,pitch:d.pitch,roll:d.roll,speed:d.speed,domain:d.altitude_m>120000?2:d.altitude_m>45000?1:0,active:this.vehicleIndex,enabled:true,runtime2:true}}));globalThis.dispatchEvent(new CustomEvent('skyrmion:runtime2-telemetry',{detail:d}));}this.dispatchEvent(new CustomEvent('telemetry',{detail:d}));}
 frame=now=>{if(!this.running)return;if(!this.lastNow)this.lastNow=now;const elapsed=Math.min(.05,(now-this.lastNow)/1000);this.lastNow=now;this.accumulator+=elapsed;let n=0;while(this.accumulator>=this.dt&&n<8){this.step();this.accumulator-=this.dt;n++;}this.emit();requestAnimationFrame(this.frame)};
 applyReplayFrame(frame){const v=vehicle(frame.vehicleId);this.vehicle=v;this.vehicleIndex=VEHICLE_ORDER.indexOf(v.id);this.state={...this.state,t:frame.t,vehicleId:v.id,position:{...frame.position},velocityBody:[...frame.velocityBody],quaternion:[...frame.quaternion],omegaBody:[...frame.omegaBody],controls:{...frame.controls}};this.emit();}
 playReplay(options={}){this.stop();return this.mission.startReplay(frame=>this.applyReplayFrame(frame),options)}
 stopReplay(){this.mission.stopReplay();this.start()}
 start(){if(this.running)return;this.running=true;this.lastNow=0;requestAnimationFrame(this.frame)} stop(){this.running=false}
 exportProof(){return {schema:'SKYRMION-RUNTIME-2-RECEIPT',generatedAt:new Date().toISOString(),runtime:this.schema,fixedStepHz:this.fixedStepHz,vehicle:this.vehicle,proof:this.proof.last,e47:this.e47.snapshot(),missionFrames:this.mission.frames.length}}
}
