/* GENERATED by scripts/generate_browser_kernel_contract.py from src/e47.
 * Do not edit by hand. Do not copy spectrum literals into runtimes.
 */
export const E47_LOCK = Object.freeze({
  "schema": "E47-CANONICAL-KERNEL-1.0",
  "authority": "src/e47/spectral_compilation.py",
  "kernel_source": "src/e47/su2_kernel.py",
  "canonical": {
    "spin": 2,
    "copies": 3,
    "selected_spins": [2, 5],
    "casimir_roots": [6, 30],
    "casimir_spectrum": [0, 2, 6, 12, 20, 30, 42],
    "sector_dimensions": [1, 9, 25, 28, 27, 22, 13],
    "carrier_dimension": 125,
    "kernel_dimension": 47,
    "coherence_fraction": "47/125",
    "kernel_polynomial": [1, -36, 180],
    "q_spectrum": [0, 11664, 12544, 19600, 32400, 186624],
    "q_gap": 11664,
    "q_max": 186624,
    "epsilon_max": "1/93312",
    "epsilon_star": "1/99144",
    "rho_star": "15/17"
  },
  "evidence": "E0/E1",
  "scope": "Finite-dimensional canonical E47 kernel contract. Browser runtimes consume this object; it does not promote simulation outputs to physical evidence."
});

export const CASIMIR = Object.freeze([0, 2, 6, 12, 20, 30, 42]);
export const MULT = Object.freeze([1, 9, 25, 28, 27, 22, 13]);
export const ROOTS = Object.freeze([6, 30]);
export const N = 125;
export const DIM_E47 = 47;
export const EPS = 1/99144;
export const OMEGA_C = 47/125;
export const Q_GAP = 11664;
export const Q_MAX = 186624;
