/* MATRIX-MPS-WORKER-1.1: real two-site MPS, complex Float64, Jacobi eigensolver SVD.\n   Worker backend contract: tensor contraction -> Schmidt/SVD -> controlled chi truncation. */
const C=(r=0,i=0)=>[r,i], add=(a,b)=>[a[0]+b[0],a[1]+b[1]], mul=(a,b)=>[a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]], conj=a=>[a[0],-a[1]], scale=(a,s)=>[a[0]*s,a[1]*s], a2=a=>a[0]*a[0]+a[1]*a[1];
const H=()=>{let q=1/Math.sqrt(2);return [C(q),C(q),C(q),C(-q)]}, R=p=>[C(1),C(),C(),C(Math.cos(p),Math.sin(p))], CNOT=[C(1),C(),C(),C(), C(),C(1),C(),C(), C(),C(),C(),C(1), C(),C(),C(1),C()];
function init(n){return Array.from({length:n},()=>({l:1,r:1,d:new Float64Array([1,0,0,0])}))}
const get=(A,l,p,r)=>[A.d[2*((l*2+p)*A.r+r)],A.d[2*((l*2+p)*A.r+r)+1]], set=(A,l,p,r,z)=>{let k=2*((l*2+p)*A.r+r);A.d[k]=z[0];A.d[k+1]=z[1]};
function one(A,U){let B={l:A.l,r:A.r,d:new Float64Array(A.d.length)};for(let l=0;l<A.l;l++)for(let r=0;r<A.r;r++)for(let o=0;o<2;o++){let z=C();for(let p=0;p<2;p++)z=add(z,mul(U[o*2+p],get(A,l,p,r)));set(B,l,o,r,z)}return B}
function hermitianEig(H,n){let V=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>C(i===j?1:0)));for(let sweep=0;sweep<80;sweep++){let changed=false;for(let p=0;p<n;p++)for(let q=p+1;q<n;q++){let hpq=H[p][q],mag=Math.sqrt(a2(hpq));if(mag<1e-13)continue;changed=true;let app=H[p][p][0],aqq=H[q][q][0],tau=(aqq-app)/(2*mag),t=(tau>=0?1:-1)/(Math.abs(tau)+Math.sqrt(1+tau*tau)),c=1/Math.sqrt(1+t*t),sr=c*t,phase=scale(hpq,1/mag),s=scale(phase,sr);
 for(let k=0;k<n;k++)if(k!==p&&k!==q){let kp=H[k][p],kq=H[k][q],np=add(scale(kp,c),mul(s,kq)),nq=add(scale(kq,c),scale(mul(conj(s),kp),-1));H[k][p]=np;H[p][k]=conj(np);H[k][q]=nq;H[q][k]=conj(nq)}
 H[p][p]=C(app-t*mag);H[q][q]=C(aqq+t*mag);H[p][q]=H[q][p]=C();
 for(let k=0;k<n;k++){let vp=V[k][p],vq=V[k][q];V[k][p]=add(scale(vp,c),mul(s,vq));V[k][q]=add(scale(vq,c),scale(mul(conj(s),vp),-1))}
 }if(!changed)break}
 let ix=Array.from({length:n},(_,i)=>i).sort((a,b)=>H[b][b][0]-H[a][a][0]);return {vals:ix.map(i=>Math.max(0,H[i][i][0])),vecs:V.map(row=>ix.map(i=>row[i]))}}
function localJacobi(a,d,b){let mag=Math.sqrt(a2(b));if(mag<1e-30)return [[C(1),C()],[C(),C(1)]];let phase=scale(b,1/mag),tau=(d-a)/(2*mag),t=(tau>=0?1:-1)/(Math.abs(tau)+Math.sqrt(1+tau*tau)),c=1/Math.sqrt(1+t*t),s=t*c,U=[[scale(phase,c),scale(phase,s)],[C(-s),C(c)]];for(let k=0;k<2;k++){let z=U[k][k],zm=Math.sqrt(a2(z));if(zm>1e-30){let ph=scale(conj(z),1/zm);U[0][k]=mul(U[0][k],ph);U[1][k]=mul(U[1][k],ph)}}return U}
function oneSidedSVD(M,maxSweeps=80,tol=1e-13){let rows=M.length,cols=M[0].length,A=M.map(row=>row.map(z=>C(z[0],z[1]))),V=Array.from({length:cols},(_,i)=>Array.from({length:cols},(_,j)=>C(i===j?1:0))),fro2=A.reduce((s,row)=>s+row.reduce((q,z)=>q+a2(z),0),0),floor=tol*tol*fro2;for(let sweep=0;sweep<maxSweeps;sweep++){let changed=false,maxCorr=0;for(let p=0;p<cols;p++)for(let q=p+1;q<cols;q++){let aa=0,dd=0,bb=C();for(let k=0;k<rows;k++){aa+=a2(A[k][p]);dd+=a2(A[k][q]);bb=add(bb,mul(conj(A[k][p]),A[k][q]))}if(aa<=floor||dd<=floor)continue;let denom=Math.sqrt(aa*dd),corr=Math.sqrt(a2(bb))/(denom||1);maxCorr=Math.max(maxCorr,corr);if(corr<=tol)continue;let U=localJacobi(aa,dd,bb);for(let k=0;k<rows;k++){let ap=A[k][p],aq=A[k][q];A[k][p]=add(mul(ap,U[0][0]),mul(aq,U[1][0]));A[k][q]=add(mul(ap,U[0][1]),mul(aq,U[1][1]))}for(let k=0;k<cols;k++){let vp=V[k][p],vq=V[k][q];V[k][p]=add(mul(vp,U[0][0]),mul(vq,U[1][0]));V[k][q]=add(mul(vp,U[0][1]),mul(vq,U[1][1]))}changed=true}if(!changed||maxCorr<=tol)break}let s=Array.from({length:cols},(_,j)=>Math.sqrt(A.reduce((x,row)=>x+a2(row[j]),0))),ix=Array.from({length:cols},(_,i)=>i).sort((a,b)=>s[b]-s[a]);return {s:ix.map(i=>s[i]),cols:A.map(row=>ix.map(i=>row[i])),vecs:V.map(row=>ix.map(i=>row[i]))}}
function two(A,B,U,chi){let L=A.l,R=B.r,ca=A.r,rows=L*2,cols=2*R,M=Array.from({length:rows},()=>Array.from({length:cols},()=>C()));
 for(let l=0;l<L;l++)for(let o1=0;o1<2;o1++)for(let o2=0;o2<2;o2++)for(let r=0;r<R;r++){let z=C();for(let a=0;a<ca;a++)for(let p1=0;p1<2;p1++)for(let p2=0;p2<2;p2++)z=add(z,mul(U[(o1*2+o2)*4+p1*2+p2],mul(get(A,l,p1,a),get(B,a,p2,r))));M[l*2+o1][o2*R+r]=z}
 let e=oneSidedSVD(M),s=e.s,maxPossible=Math.min(rows,cols),threshold=Math.max(1e-12,(s[0]||0)*1e-12),algebraic=Math.min(maxPossible,s.filter(x=>x>threshold).length||1),rank=Math.min(chi,algebraic),disc=s.slice(rank).reduce((x,y)=>x+y*y,0),tot=s.reduce((x,y)=>x+y*y,0),AA={l:L,r:rank,d:new Float64Array(2*L*2*rank)},BB={l:rank,r:R,d:new Float64Array(2*rank*2*R)};
 for(let b=0;b<rank;b++){let sv=s[b];for(let row=0;row<rows;row++)set(AA,Math.floor(row/2),row%2,b,sv>1e-14?scale(e.cols[row][b],1/sv):C());for(let col=0;col<cols;col++)set(BB,b,Math.floor(col/R),col%R,scale(conj(e.vecs[col][b]),sv))}
 return [AA,BB,{s:s.slice(0,rank),discarded:tot?disc/tot:0}]}
function amp(m,bits){let v=[C(1)];for(let q=0;q<m.length;q++){let nv=Array.from({length:m[q].r},()=>C());for(let l=0;l<m[q].l;l++)for(let r=0;r<m[q].r;r++)nv[r]=add(nv[r],mul(v[l],get(m[q],l,bits[q],r)));v=nv}return v[0]}
function dense(m){let n=m.length,N=1<<n,out=[];for(let x=0;x<N;x++)out.push(amp(m,Array.from({length:n},(_,q)=>(x>>(n-1-q))&1)));return out}
function exact(n,layers,phi){let v=Array.from({length:1<<n},(_,i)=>C(i?0:1));const apply1=(q,U)=>{let step=1<<(n-1-q);for(let base=0;base<v.length;base+=2*step)for(let k=0;k<step;k++){let i=base+k,j=i+step,a=v[i],b=v[j];v[i]=add(mul(U[0],a),mul(U[1],b));v[j]=add(mul(U[2],a),mul(U[3],b))}};const cx=q=>{let a=1<<(n-1-q),b=1<<(n-2-q);for(let i=0;i<v.length;i++)if((i&a)&&!(i&b)){let j=i|b,tmp=v[i];v[i]=v[j];v[j]=tmp}};for(let k=0;k<layers;k++){for(let q=0;q<n;q++){apply1(q,H());apply1(q,R(phi))}for(let q=k%2;q<n-1;q+=2)cx(q)}return v}
function rng(seed){let x=(seed>>>0)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function noisyTrajectory(v,n,g1,gphi,seed){let rand=rng(seed),events=0;const norm=()=>Math.sqrt(v.reduce((s,z)=>s+a2(z),0))||1, renorm=()=>{let q=norm();for(let i=0;i<v.length;i++)v[i]=scale(v[i],1/q)};
 for(let q=0;q<n;q++){let bit=1<<(n-1-q),p1=0;for(let i=0;i<v.length;i++)if(i&bit)p1+=a2(v[i]);let pj=Math.min(1,Math.max(0,g1))*p1;if(rand()<pj&&p1>1e-15){let out=Array.from({length:v.length},()=>C());for(let i=0;i<v.length;i++)if(i&bit)out[i^bit]=add(out[i^bit],v[i]);v=out;renorm();events++}else{let s=Math.sqrt(Math.max(0,1-g1));for(let i=0;i<v.length;i++)if(i&bit)v[i]=scale(v[i],s);renorm()}if(rand()<Math.min(1,Math.max(0,gphi))){for(let i=0;i<v.length;i++)if(i&bit)v[i]=scale(v[i],-1);events++}}
 return {v,events}}
onmessage=e=>{let {n,layers,phi,chi,validate,noise='none',g1=0,gphi=0,seed=47125,entangler='brickwork'}=e.data;if(noise!=='none'&&n>16){postMessage({ok:false,error:'Trajectory noise currently requires n ≤ 16 so the sampled Kraus state can be materialized exactly.'});return}let m=init(n),discard=0,lastS=[1];for(let k=0;k<layers;k++){for(let q=0;q<n;q++){m[q]=one(m[q],H());m[q]=one(m[q],R(phi))}let start=entangler==='chain'?0:k%2,step=entangler==='chain'?1:2;for(let q=start;q<n-1;q+=step){let [a,b,t]=two(m[q],m[q+1],CNOT,chi);m[q]=a;m[q+1]=b;discard+=t.discarded;lastS=t.s}}
 let vec=n<=16?dense(m):null,noiseInfo={model:'none',events:0,seed:null};if(noise==='trajectory'&&vec){let t=noisyTrajectory(vec,n,g1,gphi,seed);vec=t.v;noiseInfo={model:'amplitude-damping+phase-flip-trajectory',events:t.events,seed,gamma1:g1,gamma_phi:gphi}}let norm=vec?vec.reduce((s,z)=>s+a2(z),0):1,maxBond=Math.max(...m.map(x=>x.r));let validation=null;if(validate&&n<=10&&noise==='none'&&entangler==='brickwork'){let ref=exact(n,layers,phi),d=0,rn=0;for(let i=0;i<ref.length;i++){d+=a2([vec[i][0]-ref[i][0],vec[i][1]-ref[i][1]]);rn+=a2(ref[i])}let err=Math.sqrt(d/rn),exactBond=1<<Math.floor(n/2),untruncated=chi>=exactBond||discard<1e-14;validation={relative_l2:err,mode:untruncated?'exact-equivalence':'controlled-truncation',pass:untruncated?err<1e-9:Number.isFinite(err),tolerance:untruncated?1e-9:null}}
 postMessage({ok:true,engine:'two-site-mps',backend:'web-worker-js',precision:'complex-float64',norm,maxBond,discard,lastS,validation,noise:noiseInfo,statevector:vec?.map(z=>z)});};